/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

/**
 * The Enums SDK module.
 * @module SDK/Enums
 * @version 1.2.1
 */

export enum TokenType {
    ACCESS_TOKEN = 'access_token',
    ID_TOKEN = 'id_token'
}
