/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { exists } from '../ApiClient';
import type { CreateUserRequestIdentitiesInner } from './CreateUserRequestIdentitiesInner';
import {
    CreateUserRequestIdentitiesInnerFromJSON,
    CreateUserRequestIdentitiesInnerToJSON
} from './CreateUserRequestIdentitiesInner';
import type { CreateUserRequestProfile } from './CreateUserRequestProfile';
import {
    CreateUserRequestProfileFromJSON,
    CreateUserRequestProfileToJSON
} from './CreateUserRequestProfile';

/**
 *
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     *
     * @type {CreateUserRequestProfile}
     * @memberof CreateUserRequest
     */
    profile?: CreateUserRequestProfile;
    /**
     *
     * @type {Array<CreateUserRequestIdentitiesInner>}
     * @memberof CreateUserRequest
     */
    identities?: Array<CreateUserRequestIdentitiesInner>;
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
    return CreateUserRequestFromJSONTyped(json, false);
}

export function CreateUserRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateUserRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        profile: !exists(json, 'profile')
            ? undefined
            : CreateUserRequestProfileFromJSON(json['profile']),
        identities: !exists(json, 'identities')
            ? undefined
            : (json['identities'] as Array<any>).map(
                  CreateUserRequestIdentitiesInnerFromJSON
              )
    };
}

export function CreateUserRequestToJSON(value?: CreateUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        profile: CreateUserRequestProfileToJSON(value.profile),
        identities:
            value.identities === undefined
                ? undefined
                : (value.identities as Array<any>).map(
                      CreateUserRequestIdentitiesInnerToJSON
                  )
    };
}
