/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { exists } from '../ApiClient';
import type { User } from './User';
import { UserFromJSON, UserToJSON } from './User';

/**
 *
 * @export
 * @interface GetUsers200Response
 */
export interface GetUsers200Response {
    /**
     *
     * @type {Array<Array<User>>}
     * @memberof GetUsers200Response
     */
    users?: Array<Array<User>>;
    /**
     *
     * @type {string}
     * @memberof GetUsers200Response
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetUsers200Response interface.
 */
export function instanceOfGetUsers200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetUsers200ResponseFromJSON(json: any): GetUsers200Response {
    return GetUsers200ResponseFromJSONTyped(json, false);
}

export function GetUsers200ResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): GetUsers200Response {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        users: !exists(json, 'users') ? undefined : json['users'],
        nextToken: !exists(json, 'next_token') ? undefined : json['next_token']
    };
}

export function GetUsers200ResponseToJSON(
    value?: GetUsers200Response | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        users: value.users,
        next_token: value.nextToken
    };
}
