/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { exists } from '../ApiClient';
/**
 *
 * @export
 * @interface UserIdentityResult
 */
export interface UserIdentityResult {
    /**
     *
     * @type {boolean}
     * @memberof UserIdentityResult
     */
    created?: boolean;
    /**
     *
     * @type {number}
     * @memberof UserIdentityResult
     */
    identityId?: number;
}

/**
 * Check if a given object implements the UserIdentityResult interface.
 */
export function instanceOfUserIdentityResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserIdentityResultFromJSON(json: any): UserIdentityResult {
    return UserIdentityResultFromJSONTyped(json, false);
}

export function UserIdentityResultFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UserIdentityResult {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        created: !exists(json, 'created') ? undefined : json['created'],
        identityId: !exists(json, 'identity_id')
            ? undefined
            : json['identity_id']
    };
}

export function UserIdentityResultToJSON(
    value?: UserIdentityResult | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        created: value.created,
        identity_id: value.identityId
    };
}
