/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { exists } from '../ApiClient';
/**
 *
 * @export
 * @interface UserProfileV2
 */
export interface UserProfileV2 {
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    providedId?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    givenName?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    familyName?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfileV2
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the UserProfileV2 interface.
 */
export function instanceOfUserProfileV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileV2FromJSON(json: any): UserProfileV2 {
    return UserProfileV2FromJSONTyped(json, false);
}

export function UserProfileV2FromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UserProfileV2 {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: !exists(json, 'id') ? undefined : json['id'],
        providedId: !exists(json, 'provided_id')
            ? undefined
            : json['provided_id'],
        name: !exists(json, 'name') ? undefined : json['name'],
        givenName: !exists(json, 'given_name') ? undefined : json['given_name'],
        familyName: !exists(json, 'family_name')
            ? undefined
            : json['family_name'],
        updatedAt: !exists(json, 'updated_at') ? undefined : json['updated_at']
    };
}

export function UserProfileV2ToJSON(value?: UserProfileV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        provided_id: value.providedId,
        name: value.name,
        given_name: value.givenName,
        family_name: value.familyName,
        updated_at: value.updatedAt
    };
}
