/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

/**
 * The Oauth SDK module.
 * @module SDK/Oauth
 * @version 1.1.0
 */
class BaseStore {
    private data: Map<string, string>;

    constructor() {
        this.data = new Map<string, string>();
    }

    public getItem(key: string) {
        return this.data.get(key);
    }

    public get length() {
        return this.data.size;
    }

    public setItem(key: string, value: string) {
        this.data.set(key, value);
    }

    public removeItem(key: string) {
        this.data.delete(key);
    }

    public clear() {
        this.data = new Map<string, string>();
    }
}
export default BaseStore;
